global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodejs_app'
    static_configs:
      - targets: ['localhost:3000'] # Assuming your Node.js app runs on localhost:3000
