global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodejs_app'
    static_configs:
      - targets: ['localhost:3000']

rule_files:
  - 'alert-rules.yaml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
